version: '3.8'
services:
  dbmysql:
    image: mysql:latest
    container_name: bdbluesburger
    command: --skip-name-resolve --host-cache-size=0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbbluesburger
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - 3306
      - 33060
    networks:
      - spring-boot-mysql-network

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: amazoncorretto:11-al2023-jdk
    container_name: application-java
    ports:
      - "8181:8080"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - dbmysql
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/dbbluesburger
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    volumes:
      - db_app:/var/lib/app
    command: [ "java", "-jar", "/app/orderingsystem-0.0.1-SNAPSHOT.jar" ]

networks:
  spring-boot-mysql-network:
    driver: bridge

volumes:
  db_data:
  db_app: