version: '3.8'
services:
  dbmysql:
    image: mysql:8.0
    container_name: bdbluesburger
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbbluesburger
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - 3306
      - 33060
    networks:
      - spring-boot-mysql-network
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5
  
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: orderingsystem:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "8181:8080"
    networks:
      - spring-boot-mysql-network
    depends_on:
      dbmysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/dbbluesburger
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    volumes:
      - db_app:/var/lib/app

networks:
  spring-boot-mysql-network:
    driver: bridge

volumes:
  db_data:
  db_app:
