insert ignore into tb_dish (id, created_time, name, price, description, category, updated_time) values (1, now(), 'Faláfel', 10.00, 'Salgadinho originário do Oriente Médio que consiste em bolinhos fritos de grão-de-bico ou fava moída, normalmente misturados com condimentos como alho, cebolinha, salsa, coentro e cominho', 'DISH', now());
insert ignore into tb_dish (id, created_time, name, price, description, category, updated_time) values (2, now(), 'Peixe', 10.00, 'DISH simples e saboroso que pode ser feito com uma variedade de peixes. O peixe é cozido em água ou caldo, até que esteja cozido por dentro. O peixe pode ser cozido inteiro, em postas ou em filés.', 'DISH', now());
insert ignore into tb_dish (id, created_time, name, price, description, category, updated_time) values (3, now(), 'Gaspacho', 10.00, 'Gaspacho ou caspacho é uma sopa fria à base de hortaliças, com destaque para o tomate, o pepino e o pimentão, muito popular no sul de Portugal, no sul de Espanha, bem como no México e outros países centro-americanos', 'DISH', now());
insert ignore into tb_dish (id, created_time, name, price, description, category, updated_time) values (4, now(), 'Ramen', 10.00, 'Composto por um tipo de macarrão chinês, uma sopa com caldo à base de ossos de porco, peixe ou frango, e temperados com uma base tarê (molho) que dá sabor ao caldo base', 'DISH', now());
insert ignore into tb_dish (id, created_time, name, price, description, category, updated_time) values (5, now(), 'Macarrão Rigatoni', 10.00, 'Tipo de macarrão longo e cilíndrico com sulcos profundos. É feito de farinha de trigo, água e ovos. Os sulcos profundos do macarrão permitem que ele absorva mais molho, tornando-o um DISH de massa perfeito', 'DISH', now());
insert ignore into tb_dish (id, created_time, name, price, description, category, updated_time) values (6, now(), 'Hambúrguer', 10.00, 'Sanduíche feito com um hambúrguer de carne moída, geralmente carne bovina, colocado entre duas fatias de pão. O hambúrguer pode ser servido com uma variedade de acompanhamentos, como queijo, alface, tomate, cebola, picles, ketchup, mostarda e maionese.', 'DISH', now());

insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (1, now(), 'Margarita', 20.0, now(), 'A margarita é um coquetel feito com 45 ml de tequila, sal, 22,5 ml sumo de limão e 22,5ml xarope de agave.', 'DRINK', 1);
insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (2, now(), 'Cosmopolitan', 20.0, now(), 'Um cosmopolitan, ou simplesmente cosmo, é uma bebida alcoólica, ou um coquetel feito com vodca, triple sec, suco de oxicoco e suco de limão espremido ou adoçado.', 'DRINK', 1);
insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (3, now(), 'Daiquiri', 20.0, now(), 'Daiquiri é uma bebida alcoólica ou, um coquetel feito com rum, suco de lima, e açúcar ou xarope, de origem cubana.', 'DRINK', 1);
insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (4, now(), 'Gim', 20.0, now(), 'Gim ou gin é uma bebida destilada alcoólica feita principalmente de cereais, como cevada ou trigo, podendo ser feita também com outros tipos de álcool. Ela obrigatoriamente deve levar zimbro em sua composição, o que traz as características específicas desta bebida', 'DRINK', 1);
insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (5, now(), 'Manhattan', 20.0, now(), 'Manhattan é um coquetel feito com uísque, vermute doce e bitters. Embora a receita tradicional use uísque de centeio, também são comumente usados os uísque canadense, bourbon, blended whisky ou Tennessee whiskey.', 'DRINK', 1);
insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (6, now(), 'Negroni', 20.0, now(), 'O negroni é um coquetel feito de uma parte de gim, uma parte de vermute rosso, e uma parte de Campari, enfeitado com casca de laranja. É considerado um aperitivo. O coquetel é de origem italiana e sua receita deriva-se da receita do clássico americano.', 'DRINK', 1);
insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (7, now(), 'Old Fashioned', 20.0, now(), 'O old fashioned é uma bebida alcoólica, ou um coquetel aperitivo, feito com uísque, bíter, açúcar triturado no almofariz e guarnecido com casca de laranja e cereja. O nome significa, em inglês, significa "antiquado". É tradicionalmente servido em um copo do tipo tumbler que recebeu o mesmo nome da bebida.', 'DRINK', 1);
insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (8, now(), 'Expresso Martini', 20.0, now(), 'O espresso martini, também conhecido como vodka espresso, é uma bebida alcoólica com cafeína fria feita com espresso, licor de café e vodka. Não é um verdadeiro martini, pois não contém gim nem vermute, mas é uma das muitas bebidas que incorporam o termo martini em seus nomes', 'DRINK', 1);
insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (9, now(), 'Martini de Maracujá', 20.0, now(), 'O Martini de Maracujá é uma bebida alcoólica refrescante e saborosa que é perfeita para uma ocasião especial ou simplesmente para relaxar em um dia quente. É feito com vodka, licor de maracujá, purê de maracujá, suco de limão e xarope simples. Os ingredientes são misturados em uma coqueteleira com gelo e coados em uma taça de martini gelada.', 'DRINK', 1);
insert ignore into drink (id, created_time, name, price, updated_time, description, category, quantity) values (10, now(), 'Mimosa', 20.0, now(), 'Um coquetel de mimosa consiste em champanhe e suco cítrico gelado, geralmente suco de laranja. Muitas vezes, é servido em uma taça de champanhe alta em ocasiões festivas, como brunch, casamentos ou como parte do serviço de negócios ou de primeira classe em algumas ferrovias e companhias aéreas de passageiros.', 'DRINK', 1);

insert ignore into dessert (id, created_time, name, price, description, category, updated_time) values (1, now(), 'Bolo', 20.0, 'Os bolos são feitos com uma variedade de ingredientes, incluindo farinha de trigo, açúcar, ovos, leite, manteiga ou margarina, e fermento em pó. Também podem ser adicionados outros ingredientes, como frutas, chocolate, nozes, especiarias, etc.', 'DESSERT', now());
insert ignore into dessert (id, created_time, name, price, description, category, updated_time) values (2, now(), 'Cookie', 20.0, 'Biscoito doce e crocante, geralmente feito com farinha, açúcar, manteiga, ovos e fermento. Também podem ser adicionados outros ingredientes, como chocolate, nozes, frutas, etc.', 'DESSERT', now());
insert ignore into dessert (id, created_time, name, price, description, category, updated_time) values (3, now(), 'Biscoito', 20.0, 'Alimento à base de farinha, geralmente doce e cozido no forno. É um alimento popular em todo o mundo e pode ser encontrado em uma variedade de sabores e texturas', 'DESSERT', now());
insert ignore into dessert (id, created_time, name, price, description, category, updated_time) values (4, now(), 'Gelatina', 20.0, 'Sobremesa feita com gelatina, água ou leite e açúcar. Pode ser aromatizada com frutas, chocolate ou outros sabores. A gelatina é um alimento popular em todo o mundo e pode ser encontrada em uma variedade de formas, tamanhos e sabores', 'DESSERT', now());
insert ignore into dessert (id, created_time, name, price, description, category, updated_time) values (5, now(), 'Sorvete', 20.0, 'Sobremesa gelada feita com leite, creme, açúcar e outros ingredientes, como frutas, chocolate ou nozes', 'DESSERT', now());
insert ignore into dessert (id, created_time, name, price, description, category, updated_time) values (6, now(), 'Torta de Morango', 20.0, 'Sobremesa clássica que é amada por pessoas de todas as idades. É feito com uma massa de torta crocante, um creme de baunilha cremoso e morangos frescos e suculentos.', 'DESSERT', now());
insert ignore into dessert (id, created_time, name, price, description, category, updated_time) values (7, now(), 'Pudim', 20.0, 'Sobremesa cremosa e saborosa que pode ser servida quente ou fria. É feito com leite, ovos, açúcar e outros ingredientes, como chocolate, frutas ou nozes', 'DESSERT', now());
insert ignore into dessert (id, created_time, name, price, description, category, updated_time) values (8, now(), 'Doce', 20.0, 'Alimento doce, geralmente feito com açúcar ou adoçante artificial, e pode ser servido como sobremesa ou como lanche', 'DESSERT', now());
