apiVersion: v1
kind: ConfigMap
metadata:
  name: dados
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:mysql://dbmysql:3306/dbbluesburger"
  SPRING_DATASOURCE_USERNAME: "admin"
  DB_DATABASE: "dbbluesburger"
