apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: jdbc:mysql://svc-ordering-system-database/dbbluesburger
  MYSQL_DATABASE: dbbluesburger