apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-system-api
  labels:
    app: ordering-system-api-order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ordering-system-api-order
  template:
    metadata:
      name: ordering-system-api
      labels:
        app: ordering-system-api-order
    spec:
      containers:
        - name: orderingsystem
          image: leandroaraujosp/orderingsystem:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/v1/order/all/PREPARO_INICIADO
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/order/all/PREPARO_INICIADO
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 30
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: ordering-system-opaque
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ordering-system-opaque
                key: SPRING_DATASOURCE_PASSWORD