apiVersion: v1
kind: Secret
metadata:
  name: ordering-system-opaque
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: admin
  MYSQL_ROOT_PASSWORD: "123456"
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin