apiVersion: v1
kind: Pod
metadata:
  name: ordering-system-api
  labels:
    app: ordering-system-api-order
spec:
  containers:
    - name: orderingsystem
      image: leandroaraujosp/orderingsystem:0.0.1-SNAPSHOT
      ports:
        - containerPort: 8080
      env:
      - name: SPRING_PROFILES_ACTIVE
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: SPRING_PROFILES_ACTIVE
      - name: SPRING_DATASOURCE_URL
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: SPRING_DATASOURCE_URL
      - name: SPRING_DATASOURCE_USERNAME
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: SPRING_DATASOURCE_USERNAME
      - name: SPRING_DATASOURCE_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: SPRING_DATASOURCE_PASSWORD