apiVersion: v1
kind: Pod
metadata:
  name: ordering-system-database
  labels:
    app: ordering-system-database1
spec:
  containers:
    - name: dbmysql
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"
      - name: MYSQL_DATABASE
        value: "dbbluesburger"
      - name: MYSQL_USER
        value: "admin"
      - name: MYSQL_PASSWORD
        value: "admin"