apiVersion: v1
kind: Service
metadata:
  name: svc-ordering-system-api
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31080
      targetPort: 8080
  selector:
    app: ordering-system-api-order