apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-mysql # name of PVC essential for identifying the storage data
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  volumeMode: Filesystem
  resources:
    requests:
      storage: 15Gi    #This will tell kubernetes about the amount of space we are trying to claim.
  storageClassName: csi-hostpath-sc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-hostpath-sc
provisioner: docker.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    app: mysql
    tier: database
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/d/_development/postech/ordering-system/volumes/data"
  storageClassName: csi-hostpath-sc
  persistentVolumeReclaimPolicy: Retain
