apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-mysql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 15Gi
  storageClassName: csi-hostpath-sc