apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ordering-system-database-pvc
  labels:
    name: ordering-system-database-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi