apiVersion: v1
kind: PersistentVolume
metadata:
  name: ordering-system-database-pv
  labels:
    name: ordering-system-database-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
        path: /run/desktop/mnt/host/d/_development/postech/ordering-system/volumes/data