apiVersion: v1
kind: Pod
metadata:
  name: ordering-system-database
  labels:
    app: ordering-system-database1
spec:
  containers:
    - name: dbmysql
      image: mysql:8.0
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: database
          mountPath: /var/lib/mysql
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ordering-system-opaque
            key: MYSQL_ROOT_PASSWORD
      - name: MYSQL_DATABASE
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: MYSQL_DATABASE
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: ordering-system-opaque
            key: MYSQL_USER
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ordering-system-opaque
            key: MYSQL_PASSWORD
  volumes:
    - name: database
      hostPath:
        path: /run/desktop/mnt/host/d/_development/postech/ordering-system/volumes/data